### ISSUE TITLE
Project in working condition?

### ISSUE THREAD

**Issue by apoorvkh** [Octavian-ai/BigGAN-TPU-TensorFlow#1]
Hi,

I'm trying to train BigGAN on a dataset and see this is a recent project -- I have a few questions. Have you had success/progress with training on ImageNet so far? Are there any specific training scripts that are or are not currently working? What tpu-size are you using?

Thanks!

**Comment by davidhughhenrymack** [comment]
Hi, Thanks for the questions!

I’ve been debugging the model, and am now running it on ImageNet again to
see how well it does.

The best way for you to demo it is to run the MNIST or cifar launch
scripts. They’ll quickly train to reasonable looking results (e.g. MNIST
perfectly conditions and makes nice looking digits).

I’m generally running on a single TPU (=8 cores) as that’s all I can get my
hands on

Does that help? Can I answer any more / encourage you to contribute?


On March 16, 2019 at 3:10:16 PM, Apoorv Khandelwal (notifications@github.com)
wrote:

Hi,

I'm trying to train BigGAN on a dataset and see this is a recent project --
I have a few questions. Have you had success/progress with training on
ImageNet so far? Are there any specific training scripts that are or are
not currently working? What tpu-size are you using?

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Octavian-ai/BigGAN-TPU-TensorFlow/issues/1>, or mute
the thread

**Comment by davidhughhenrymack** [comment]
Oh one more thing - you can see my training runs (live and previous) here:
https://www.comet.ml/davidhughhenrymack/biggan


On March 16, 2019 at 3:15:34 PM, David Mack (davidhughhenrymack@gmail.com)
wrote:

Hi, Thanks for the questions!

I’ve been debugging the model, and am now running it on ImageNet again to
see how well it does.

The best way for you to demo it is to run the MNIST or cifar launch
scripts. They’ll quickly train to reasonable looking results (e.g. MNIST
perfectly conditions and makes nice looking digits).

I’m generally running on a single TPU (=8 cores) as that’s all I can get my
hands on

Does that help? Can I answer any more / encourage you to contribute?


On March 16, 2019 at 3:10:16 PM, Apoorv Khandelwal (notifications@github.com)
wrote:

Hi,

I'm trying to train BigGAN on a dataset and see this is a recent project --
I have a few questions. Have you had success/progress with training on
ImageNet so far? Are there any specific training scripts that are or are
not currently working? What tpu-size are you using?

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Octavian-ai/BigGAN-TPU-TensorFlow/issues/1>, or mute
the thread

**Comment by apoorvkh** [comment]
Thanks! I'll let you know if I decide to try it out. One more question - is that a v2 or v3 TPU?

**Comment by davidhughhenrymack** [comment]
I used the v2.8 as it’s all I have access to. I want to get access to a pod


On March 16, 2019 at 4:13:21 PM, Apoorv Khandelwal (notifications@github.com)
wrote:

Thanks! I'll let you know if I decide to try it out. One more question - is
that a v2 or v3 TPU?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Octavian-ai/BigGAN-TPU-TensorFlow/issues/1#issuecomment-473600390>,
or mute the thread

**Comment by apoorvkh** [comment]
Sounds good. Thanks!
